// Catálogo de servicios de mantenimiento/reparación (documento "CUERPO").
// Cada grupo es el nombre que se guarda en `descripcion`; sus ítems se
// acumulan como líneas en `subItems` cuando se seleccionan desde el panel.
export const CATALOGO_SERVICIOS = [
  { grupo: "Desmontaje y Montaje de Motor", items: [
    "Gestionar permisos para trabajos con energía peligrosa.",
    "1. Bloqueo de energías peligrosas (Eléctrica, hidráulica, presión, etc)",
    "2. Desconexión eléctrica.",
    "3. Desmontaje motor eléctrico en lugar de trabajo.",
    "4. Traslado a nuestra instalación y posterior retorno a planta",
    "5. Montaje en lugar de trabajo y conexión eléctrica.",
    "6. Puesta en funcionamiento",
  ]},
  { grupo: "Mantenimiento del Estator", items: [
    "1. Evaluación y diagnóstico del bobinado.",
    "2. Pruebas eléctricas estáticas (Norma 43-2000) - Schleich",
    "— Resistencia de aislamiento",
    "— Índice de polarización",
    "— Índice de absorción dieléctrica",
    "— Prueba Surge",
    "— Prueba Hipot",
    "3. Medida de aislamiento",
    "4. Lavado con solvente dieléctrico (Hasta levantar el nivel de aislamiento)",
    "5. Tratamiento térmico (Hasta levantar el nivel de aislamiento)",
    "6. Doble barnizado.",
    "7. Secado al horno",
    "8. Pruebas eléctricas en taller: Índice de polaridad, absorción y If.",
    "9. Verificación de ajuste de tapas. Corrección de ser necesario (metalizado)",
    "10. Verificación del estado de las contratapas.",
    "11. Cambio de pernos dañados",
    "12. Pintura en general y entrega de informe fotográfico",
  ]},
  { grupo: "Rebobinado del Estator", items: [
    "1. Evaluación y diagnóstico del bobinado.",
    "3. Rebobinado del estator",
    "4. Tratamiento térmico",
    "5. Doble impregnación de barniz termo clad marca Dolph's.",
    "6. Tratamiento térmico (Hasta levantar el nivel de aislamiento)",
    "7. Acabado con resina epóxica.",
    "8. Secado al horno",
    "9. Pruebas eléctricas estáticas (Norma 43-2000) - Schleich",
    "— Resistencia de aislamiento",
    "— Índice de polarización",
    "— Índice de absorción dieléctrica",
    "— Prueba Surge",
    "— Prueba Hipot",
    "10. Verificación de ajuste de tapas.",
    "11. Cambio de pernos dañados",
    "12. Pintura en general y entrega de informe fotográfico",
  ]},
  { grupo: "Mantenimiento del Rotor", items: [
    "1. Evaluación y diagnóstico de la jaula de ardilla.",
    "2. Verificación de paralelismo del eje.",
    "3. Verificación de ajuste en el eje. Corrección de ser necesario (metalizado)",
    "4. Lavado con solvente dieléctrico.",
    "5. Balanceo dinámico en mesa de balanceo con equipo SEMAPI.",
    "6. Según normas de balance residual ISO 1940 y tabla de severidad según ISO 10816-4",
    "7. Pintura",
    "8. Cambio de rodamientos rígido de bolas en SKF o FAG.",
    "9. Entrega de informe fotográfico",
  ]},
  { grupo: "Mantenimiento de Electrobomba", items: [
    "Incluye suministro e instalación de sello mecánico",
    "Verificación de ajuste en el eje del sello mecánico. Corrección de ser necesario (metalizado)",
    "Evaluación y diagnóstico del impulsor",
  ]},
  { grupo: "Reparación de Electrobomba", items: [
    "Incluye suministro e instalación de sello mecánico",
    "Verificación de ajuste en el eje del sello mecánico. Corrección de ser necesario (metalizado)",
    "Evaluación y diagnóstico del impulsor",
  ]},
  { grupo: "Mantenimiento de Bomba", items: [
    "Verificación de ajuste de alojamiento de rodamiento. Corrección de ser necesario (metalizado)",
    "Verificación de ajuste en el eje del sello mecánico. Corrección de ser necesario (metalizado)",
    "Evaluación y diagnóstico del impulsor",
    "Incluye suministro e instalación impulsor",
    "Incluye suministro e instalación de sello mecánico",
    "Incluye suministro e instalación de rodamientos en SKF o FAG",
  ]},
  { grupo: "Reparación de Bomba", items: [
    "Verificación de ajuste de alojamiento de rodamiento. Corrección de ser necesario (metalizado)",
    "Verificación de ajuste en el eje del sello mecánico. Corrección de ser necesario (metalizado)",
    "Evaluación y diagnóstico del impulsor.",
    "Incluye suministro e instalación impulsor",
    "Incluye suministro e instalación de sello mecánico",
    "Incluye suministro e instalación de rodamientos en SKF o FAG",
  ]},
  { grupo: "Mantenimiento de Reductor", items: [
    "Verificación de ajuste de alojamiento de rodamiento. Corrección de ser necesario (metalizado)",
    "Verificación del ajuste del hueco de la salida del reductor.",
    "Evaluación y diagnóstico de los piñones",
    "Incluye suministro e instalación de retenes",
    "Incluye suministro e instalación de rodamientos en SKF o FAG",
    "Incluye suministro de lubricante Omala",
    "Suministro e instalación de empaque de reductor",
  ]},
  { grupo: "Reparación de Reductor", items: [
    "Verificación de ajuste de alojamiento de rodamiento. Corrección de ser necesario (metalizado)",
    "Verificación del ajuste del hueco de la salida del reductor.",
    "Evaluación y diagnóstico de los piñones",
    "Incluye suministro e instalación piñones",
    "Incluye suministro e instalación de retenes",
    "Incluye suministro e instalación de rodamientos en SKF o FAG",
    "Incluye suministro de lubricante Omala",
    "Suministro e instalación de empaque de reductor",
  ]},
  { grupo: "Balanceo Dinámico", items: [
    "Gestionar el permiso de trabajo de alto riesgo",
    "Inspección visual, preparación y seguridad",
    "Medición inicial",
    "Colocación de masa de prueba",
    "Cálculo y corrección",
    "Colocación de masa de corrección",
    "Verificación final",
    "Según normas de balance residual ISO 1940 y tabla de severidad ISO 10816-4",
    "Elaboración de informe",
  ]},
  { grupo: "Alineamiento de Ejes por Láser", items: [
    "Gestionar el permiso de trabajo de alto riesgo",
    "Inspección visual, preparación y seguridad (Apagar y bloquear el equipo)",
    "Corrección de la pata coja (Soft Foot)",
    "Preparación de la medición",
    "Toma de lecturas",
    "Cálculo de desalineación",
    "Ajuste y corrección en plano vertical y horizontal",
    "Colocación de lainas calibradas SKF",
    "Verificación final",
    "Elaboración de informe",
  ]},
  { grupo: "Alineamiento de Poleas por Láser", items: [
    "Gestionar el permiso de trabajo de alto riesgo",
    "Inspección visual, preparación y seguridad (Apagar y bloquear el equipo)",
    "Instalación de sensores",
    "Corrección angular",
    "Corrección paralela",
    "Colocación de lainas calibradas SKF",
    "Tensión y ajuste de fajas con sensor óptico",
    "Verificación final",
    "Elaboración de informe",
  ]},
];
